// Run against `wrangler dev`: node tests/integration.mjs. Writes test-only local history.
import assert from 'node:assert/strict';
const base = 'http://127.0.0.1:8787';
const initial = await fetch(`${base}/api/verbs`);
assert.equal(initial.status, 200);
const cookie = initial.headers.get('set-cookie').split(';')[0];
const verbs = await initial.json();
assert.equal(verbs.length, 110); assert.ok(!('participle' in verbs[0]));
async function send(answer, id = crypto.randomUUID(), origin = base, mode = 'standard') {
  const response = await fetch(`${base}/api/attempts`, { method: 'POST', headers: { Cookie: cookie, Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ id, verbId: 'essen', answer, mode }) });
  return { response, body: await response.json() };
}
const id = crypto.randomUUID();
const correct = await send('gegessen', id); assert.equal(correct.body.result, 'correct');
assert.match(correct.body.answered_at, /^\d{4}-\d\d-\d\dT.*\.\d{3}Z$/);
assert.deepEqual((await send('gegessen', id)).body, correct.body);
assert.equal((await send('gegesen')).body.result, 'typo');
assert.equal((await send('banana')).body.result, 'wrong');
assert.equal((await send('gegessen', crypto.randomUUID(), 'https://other.example')).response.status, 403);
assert.equal((await send(' '.repeat(3))).response.status, 400);
const progress = await (await fetch(`${base}/api/progress`, { headers: { Cookie: cookie } })).json();
assert.deepEqual(progress.summary, { total: 3, correct: 1, typo: 1, wrong: 1, practiced: 1 });
const regular = await (await fetch(`${base}/api/progress?type=regular`, { headers: { Cookie: cookie } })).json();
assert.equal(regular.summary.total, 0);
const trend = await (await fetch(`${base}/api/trends`, { headers: { Cookie: cookie } })).json();
assert.equal(trend.lesson.length, 3);
assert.ok(Math.abs(trend.lesson.at(-1).accuracy - 50) < 0.001);
assert.equal(trend.days.reduce((total, day) => total + day.total, 0), 3);
const emptyTrend = await (await fetch(`${base}/api/trends?type=regular`, { headers: { Cookie: cookie } })).json();
assert.equal(emptyTrend.lesson.length, 0);
assert.equal(emptyTrend.days.length, 0);
const get = async path => (await fetch(base + path, { headers: { Cookie: cookie } })).json();
const errors = await get('/api/common-errors');
assert.deepEqual(errors.map(verb => verb.id), ['essen']);
assert.equal(errors[0].participle, 'gegessen');
const targetedId = crypto.randomUUID();
const targeted = await send('gegessen', targetedId, base, 'errors');
assert.equal(targeted.body.practice_mode, 'errors');
assert.deepEqual((await send('gegessen', targetedId, base, 'errors')).body, targeted.body);
assert.equal((await get('/api/progress')).summary.total, 3);
assert.equal((await get('/api/progress?mode=errors')).summary.total, 1);
assert.equal((await get('/api/progress?mode=all')).summary.total, 4);
assert.equal((await get('/api/trends')).lesson.length, 3);
assert.equal((await get('/api/trends?mode=errors')).lesson.length, 1);
assert.equal((await get('/api/trends?mode=all')).lesson.length, 4);
assert.equal((await get('/api/trends')).days.reduce((sum, day) => sum + day.total, 0), 3);
assert.equal((await get('/api/trends?mode=errors')).days.reduce((sum, day) => sum + day.total, 0), 1);
assert.deepEqual(await get('/api/common-errors'), errors);
assert.equal((await send('gegessen', crypto.randomUUID(), base, 'invalid')).response.status, 400);
assert.equal((await fetch(`${base}/api/progress?mode=invalid`)).status, 400);
assert.deepEqual(await (await fetch(`${base}/api/common-errors`)).json(), []);
const separate = await (await fetch(`${base}/api/progress`)).json(); assert.equal(separate.summary.total, 0);
assert.equal((await fetch(`${base}/api/progress?type=invalid`)).status, 400);
for (const path of ['/', '/progress.html', '/js/practice.js', '/js/progress.js', '/style.css']) assert.equal((await fetch(base + path)).status, 200, path);
console.log('Integration passed: grading, timestamps, retries, filters, isolation, validation and static routes.');
